#!/bin/sh
# postinst script for cdr-client
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

package_type=deb

USER="${SUDO_USER}"
#PACKAGE_NAME="cdr-client"
INSTALL_DIR=$(find /opt -name "cdr-client" 2>/dev/null | head -n 1)
#INSTALL_DIR="$(dirname $(readlink -f $0))/.."

case "$1" in
    configure)
      # Change the owner of the installed files
      chown -R ${USER} ${INSTALL_DIR}
      echo "Owner of ${INSTALL_DIR} changed to ${USER}"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
