client:
  file-synchronization-enabled: true
  local-folder: ${java.io.tmpdir}
  idp-credentials:
    tenant-id: value-required
    client-id: value-required
    client-secret: value-required
    scope: https://identity.health.swisscom.ch/CdrApi/.default
    renew-credential: false
    last-credential-renewal-time: 1970-01-01T00:00:00Z
  file-busy-test-strategy: file_size_changed # valid values are `never_busy`, `file_size_changed`, `always_busy`
  cdr-api:
    scheme: https
    port: 443
    host: cdr.health.swisscom.ch
    base-path: api/documents
  credential-api:
    scheme: ${client.cdr-api.scheme}
    port: ${client.cdr-api.port}
    host: ${client.cdr-api.host}
    base-path: api/client-credentials
  customer:
